version: "3"

services:
  widgetbook:
    container_name: pent_day_2024_storybook
    build:
      context: ./

  pent_slides:
    container_name: pent_day_2024_slides
    build:
      context: ./Dockerfile.slides

networks:
  default:
    external: true
    name: npm