name: widgetbook_workspace
description: "A workspace for Widgetbook."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0
  pent_day_2024: 
    path: ../
  figma_frame_inspector: 
    git: 
      url: https://github.com/mark-sdb/figma-frame-inspector.git
      ref: main
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  widgetbook_generator: ^3.7.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
